# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
  web:
    image: historyservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
volumes:
  db: